GameServer.js
PlayerTracker.js

-Fixes lag that occurs after the server has been up for a while
-Potentially fixed a bug where viruses would not stop spawning
-Added a max connections value to the config

Very Important Fixes

---

GameServer.js
PacketHandler.js
PlayerTracker.js
README.md
entity/Cell.js
entity/EjectedMass.js
entity/Food.js
entity/PlayerCell.js
entity/Virus.js
entity/index.js
gamemodes/Custom.js
gamemodes/FFA.js
gamemodes/Mode.js
gamemodes/Teams.js
gamemodes/index.js
index.js
packet/UpdateLeaderboard.js

-Also a very important fix for cells getting stuck

Lots of refactoring

---

GameServer.js
PacketHandler.js
PlayerTracker.js
README.md
ai/BotLoader.js
ai/BotPlayer.js
ai/FakeSocket.js
ai/Readme.txt
entity/Cell.js
entity/EjectedMass.js
entity/PlayerCell.js
entity/Virus.js
packet/UpdateNodes.js

-Playerbots are a work in progress
-Hopefully the optimizations reduce some of the lag that populated servers get
-Also fixed "ghost" cells

Added playerbots and some optimizations to the main loop

---

README.md
src/modules/CommandList.js

-Automatically reloads the config values into the server

Forgot to merge this commit

---

src/GameServer.js
src/gamemodes/HungerGames.js
src/gamemodes/Tournament.js
src/gameserver.ini
src/index.js
src/modules/log.js

-Implemented logging system
-2 new commands
-Refactored some code

Latest updates

---

src/gamemodes/TeamX.js

1. Eject Virus will splitting it by default (configurable in code).
```javascript
this.pushVirus = false; // true: pushing virus, false: splitting virus
```
1. Fix issue: player is killed by teammate.

Fix TeamX mode

---

README.md
ogar-linux-script.sh

Now uses a function, now blocks non-absolute paths, and during updating asks if the user wants a fresh config file

---

src/GameServer.js
src/entity/Cell.js
src/entity/EjectedMass.js
src/entity/Food.js
src/gamemodes/TeamX.js
src/gamemodes/TeamZ.js

This is to replace the request #154. This can be merged automatically.
PS. The old `collisionCheck()` function is kept for box-things checking, such as `visibleCheck()`, `getNearestVirus()`, etc...

Fix collision checking by square - Collision checking by circle now

---

README.md
src/index.js
src/modules/CommandList.js

Fix some commands

---

src/GameServer.js
src/entity/Cell.js
src/gameserver.ini

I added an option in ```gameserver.ini``` that lets users change the speed of cells. Normally to change the speed the use would have to go into the code and modify a specific line in ```Cell.js```. Hope this helps!

Add player speed option

---

src/botnames.txt

(Updated Botnames To Every Skin)

---

src/modules/CommandList.js

Added structure of arguments to help menu

More description on help menu

---

src/GameServer.js

I've improved the colors. Now the colors are generated automaticaly and are much beautyful and much like the original agar.io colors.

Updated Colors

---

src/GameServer.js
src/entity/PlayerCell.js

I've found that is better to move the cells close to the mouse first.

Updated move engine

---

src/modules/CommandList.js

I've added the kickbot command

Kickbot command

---

src/GameServer.js
src/gameserver.ini

I've added eject mass cooldown.

Added eject mass cooldown

---

src/ai/BotPlayer.js
src/ai/Readme.txt

Also, looks like my editor removed some extraneous trailing whitespace.

Improvements to AI code

---

src/entity/Food.js
src/gamemodes/Experimental.js

bug: fix logic of food mass grow possibility
bug: fix server crash issue in experimental modes due to food mass grow feature

bug fixes for food mass grow feature

---

src/gamemodes/TeamX.js

Without this, you'll get an error
```
TypeError: Cannot read property 'config' of undefined
at Cell.Food (C:\Users\XXXX\Desktop\Ogar-master\src\entity\Food.js:11:24)
at Cell.MotherCell.spawnFood (C:\Users\XXXX\Desktop\Ogar-master\src\gamemodes\TeamX.js:404:13)
at Cell.MotherCell.update (C:\Users\XXXX\Desktop\Ogar-master\src\gamemodes\TeamX.js:341:18)
at Mode.TeamX.updateMotherCells (C:\Users\XXXX\Desktop\Ogar-master\src\gamemodes\TeamX.js:47:16)
at Mode.TeamX.onTick (C:\Users\XXXX\Desktop\Ogar-master\src\gamemodes\TeamX.js:299:14)
at GameServer.gamemodeTick (C:\Users\XXXX\Desktop\Ogar-master\src\GameServer.js:367:19)
at GameServer.mainLoop (C:\Users\XXXX\Desktop\Ogar-master\src\GameServer.js:387:29)
at wrapper [as _onTimeout] (timers.js:275:19)
at Timer.listOnTimeout (timers.js:92:15)
```

Fixed bug (food grow feature) in Experimental Teams

---

src/entity/PlayerCell.js

I've found that a cell looks kinda weird when it stays next to the border so I made it impossible to get closer that a a quarter of the diameter of your cell.

Border update

---

src/PacketHandler.js
src/PlayerTracker.js
src/packet/UpdateNodes.js

Each client is provided with a different, randomized coordinate system. This thwarts communication between minion bots and a cheating player.
There are no visible effects to the average player. When a cheating player tries to use a minion bot service, the bots will wander in random directions.
Minimal cost, computationally inexpensive anti-bot measure.

Coordinate system obfuscation as an anti-bot measure

---

src/GameServer.js
src/entity/PlayerCell.js

Instead of counting down the ticks left to merge until 0, count from 0 until it reaches the threshold. Making a way of merging a lot more similar to agar.io one.

Revamp the way cells merge

---

src/GameServer.js

Forgot to change eating definition at GameServer.js. This will change it.

Fix impossible merging

---

src/modules/CommandList.js

Another "undefined gameServer" bug when using the food command

---

src/GameServer.js
src/gamemodes/FFA.js
src/gameserver.ini

credits to @Andrews54757 
and a minor tweak to edit the config value's name

new config to control max players displayed on leaderboard 

---

src/GameServer.js
src/PlayerTracker.js

God damnit `playerTracker` I needed to use `(client).playerTracker.getScore();` instead of `(client).getScore();`, but still, this update will **rock**!

Free-roam mode update

---

src/entity/PlayerCell.js
src/entity/Virus.js
src/gamemodes/Teams.js

- Small cells won't push as much anymore!
- Fixed team mode small cells pushing as hard as big
- Viruses explode players with ejected cells having 24+ mass instead of 36+
- Reinvented big split cells so that it can go into infinity

Final fix for collision, and virus update

---

src/GameServer.js
src/entity/Virus.js

Fix virus bug & its weird collision

---

ogar-linux-script.sh

I have switched the if statements to case statements that call functions, so it is both easier to read and easier to copy just one function.

Fix installer readability

---

src/GameServer.js
src/entity/Cell.js
src/entity/EjectedMass.js

- Ejected cell collision  _(Too speedy cells isn't much of a problem though)_
- More smoothness on creating ejected cells & viruses
- Referenced gameServer on creating all types of cells
- Ejected cells now have an owner
- As ejected cells have an owner, overriding two functions
- Exchanging mass to same team players is not punished
- And more

Ejected cell collision and a lot of tweaks

---

src/GameServer.js

Accidentally overwrote splitting anti-team effect

---

src/GameServer.js
src/PlayerTracker.js
src/entity/Cell.js
src/entity/EjectedMass.js
src/entity/PlayerCell.js
src/entity/Virus.js
src/gamemodes/Experimental.js
src/gamemodes/HungerGames.js
src/gamemodes/Teams.js

Apply formatting rules.

---

src/GameServer.js

The bug is the server crashes after a while because of the teaming update

Fix undefined player tracker bug

---

src/gamemodes/Experimental.js

- Revamped eating collision check (used way similar to player cell
collision)
- The larger map it is, the more mother cells there are. Defaulting to 7
for an agar.io map size
- Mother cells will also check for nearby viruses
**Found a bug with ejected cells: They won't be absorbed by player cells when player is splitting**

Updates on mother cell

---

Install Dependencies.bat
README.md
src/GameServer.js
src/PlayerTracker.js
src/entity/PlayerCell.js
src/modules/CommandList.js

**Also inclues a batch file for installing dependencies for Windows**
The formatting is crap because I should be in sleep already...

Fix merge command not working

---

src/PlayerTracker.js

Fixed spectate bug caused not removing destroyed cells.

Fix spectate bug

---

src/PlayerTracker.js

Fixed a bug caused the client to forget your own cell if it's out of your viewbox for a while. (it can happen if there is large distance between your cells)

Fix view range bug

---

src/GameServer.js
src/entity/Cell.js
src/entity/PlayerCell.js
src/entity/Virus.js
src/gamemodes/Experimental.js

Also includes some other minor edits.
- `GameServer.js` - More split smoothness
- `GameServer.js` - Simplified cell creation function
- `Cell.js` - Formatting & created collisionRestoreTicks
- `PlayerCell.js` - Realistic eating range & usage of collisionRestoreTicks
`Virus.js`
- Referenced createPlayerCell
- Small cells now have a random angle
- The big cell loop was edited a bit
- `Experimental.js` - Even more realism at virus pushing and creating pellets

Smooth splitting update

---

src/entity/Cell.js

Simply put it had unwanted consequences such as:
- losing half your mass
xD

Fix autosplit not working correctly

---

src/entity/Cell.js

Fix yet another mistake at autosplit

---

src/entity/Cell.js

Fix autosplit not actually counting eaten mass

---

src/GameServer.js
src/PlayerTracker.js
src/entity/EjectedMass.js
src/entity/Virus.js

Better anti-teaming

---

src/PlayerTracker.js
src/entity/EjectedMass.js
src/entity/PlayerCell.js

Well it checked to add W multiplier for EVERY cell you eject...

Anti-teaming more friendly to self-feed

---

src/ai/BotPlayer.js
src/ai/Readme.txt

- Bots won't passively gain mass when running anymore
- Bots will target with their largest cell when chasing enemies
- Bots will update once one of three possibilities are made:
- Bot is staying in one place
- Target is out of range/eaten
- 10% random chance
Not mentioned in the readme.txt, they won't update while server is paused anymore.

More updates to bots

---

src/GameServer.js
src/entity/PlayerCell.js
src/gameserver.ini

Resolves #422
todo: make it toggleable. I had to go.

Stop grow by bots at 625 mass

---

src/packet/UpdateLeaderboard.js

Fix leaderboard bug

---

Dockerfile
docker-compose.yml

- Install Docker
- Install Docker Compose
- Navigate to directory
- Run command docker-compose run -d web
- On browser, go to http://agar.io?ip=localhost:8181
- To change the ip, modify it in `docker-compose.yml`

Added ability to run server directly using Docker.

---

src/GameServer.js
src/gameserver.ini

ejectMassCooldown default set to 100 ms

---

src/GameServer.js
src/modules/CommandList.js

Frequently calling of status and playerlist commands on my server for monitoring add some annoyance in my mood. So i decided to make aliases for them. Also made memory displaying in megabytes instead of kilobytes. And added command "kickall".

Some commands improvements

---

src/GameServer.js
src/PlayerTracker.js
src/entity/Cell.js
src/modules/CommandList.js

I was able to run 200 bots without any lag at start. Because of the bot's inefficient update mechanism capacity was decreasing slowly. I don't know for efficiency with players but must be a lot better.
It utilizes free ticks between client update (49 free ticks) and move engine (24 free, 17 utilized). 17 utilized for move engine because it apparently made player cells move slowly, so moved it to 18 ticks for an update.

Massive perfomance overhaul

---

package.json
src/GameServer.js
src/NodeHandler.js
src/PlayerHandler.js
src/PlayerTracker.js
src/entity/Cell.js
src/entity/EjectedMass.js
src/entity/PlayerCell.js
src/entity/Virus.js
src/modules/Vector.js

Want to hear about the new anti-teaming - how solo can it be?
- Doesn't punish players exploding constantly unless you lose some mass
- Doesn't punish self-feeding harshly
Check these things:
- Lose or gain mass quickly
- W team with bot/player
- Do some cell giving with teammate

Resolve #620, fix bugs, improve anti-teaming

---

src/PlayerTracker.js

Resolve #635

---

src/entity/Virus.js

Uses new virus split algorithm.
Currently buggy while having small amount of mass. I'll fix that later.
**If you can please attempt a few popsplits using this algorithm!**
Brb getting some popsplits :D

Popsplit is now guaranteed to work

---

src/packet/DynamicBuffer.js

3x faster speed while adding bytes.

Remove unnecessary flush function

---

src/GameServer.js
src/PacketHandler.js
src/PlayerTracker.js
src/entity/Cell.js
src/entity/PlayerCell.js
src/entity/Virus.js
src/gameserver.ini
src/modules/Rectangle.js
src/modules/Vector.js

Along with a few more bugfixes, most notable ones being:
- players (bots also affected) can sometimes move into NaN. This has been fixed
- No more 0 cell spawning when exploding on virus with small mass

Fix incorrect bouncing sometimes, players see cells in center on join, gameserver.ini tweaks

---

src/GameServer.js
src/NodeHandler.js
src/PlayerHandler.js
src/PlayerTracker.js
src/ai/BotLoader.js
src/entity/Food.js
src/entity/Virus.js
src/gamemodes/Experimental.js
src/gamemodes/FFA.js
src/gameserver.ini
src/modules/CommandList.js
src/modules/QuadTree.js
src/modules/Rectangle.js
src/packet/AddNode.js
src/packet/DynamicBuffer.js
src/packet/UpdateNodes.js

Todo:
- fix players' cells disappearing from view when out of borders
- enhance perfomance by a lot by not binding food nodes to NodeHandler

Perfomance optimization, two new scramblers, implement quadtree

---

src/index.js

In the comment, you said "Too lazy to learn async". Well, now its done! I originally did it for https://github.com/AJS-development/OpenAgar/blob/master/source/core/shellService.js, but I thought, "Why should I just help myself?" . So I decided to allow Ogar to have that code. 
1. It is much more efficient: OpenAgar wasn't efficient at the beginning, so Readline would just freeze when there was lag. So I made it async and it worked even during lag. (Now though, OpenAgar is the most efficient agar.io server available)
2. It has all the features of readline: I even added the "remembering" feature that allows you to use the arrow keys to see the commands you made earlier
1. Not much but there are tiny things that are easily fixable. 
1. I didn't add fancy text support but you can add them by …

Make the console async

---

src/GameServer.js
src/Start-linux.sh
src/Start-windows.bat
src/gameserver.ini
src/index.js
src/modules/CommandList.js
src/modules/log.js

Memory leak-proof, don't worry, doesn't show any problems of it for me.
- Adds new command `restart`
- Has many uses, see `restart help` or `restart ?` for info
- Also reverts Andrews' async console input because:
- Repeated command inputs will appear multiple times when looking for command with arrow-up key
- Backspace doesn't work
- Possible memory leaks
- I/O being backed up by server processing should not happen anymore, and even if it is, EVERYTHING will be backed up irreversibly until server processing ends, thus making it async is useless as node.js is single-cored
- Added `--expose-gc` argument to enable force garbage collecting when restarting
- Added config for periodical restarting of the server

Server restarting without external looping

---

package.json
src/index.js

So after @Luka967 mentioned the windows bug, I fixed it. But then, as I fixed it, I thought "Why don't I make it better?". So, I streamlined the entire thing into a module. And it has all you need. 
CHANGES
1. Works for any OS
2. Left and right keys now allow you to edit your typed command
3. The module now has an easy way to use it
4. Fixed every bug I mentioned in #670 
MODULE SPECS:
Usage:
```
var AsyncConsole = require('asyncconsole');
var input = new AsyncConsole("> ",function(str) { // arguments: AsyncConsole(prompttext,callback,test?)
// do something with str.
})
// other things:
input.pause() // pause it
input.resume() // resume
input.up() // stimulate up key
input.down() // stimulate down key
input.left() // stimulate left key
input.right() // stimulate right key
input.enter() // …
```

Perfected Async Console.
